"""empty message

Revision ID: 053a4800c54a
Revises: a2cf304fd7ae
Create Date: 2025-12-18 16:09:37.272775

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '053a4800c54a'
down_revision = 'a2cf304fd7ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instruments', schema=None) as batch_op:
        batch_op.alter_column('machine_type',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.Enum('HEMATOLOGY', 'CHEMISTRY', 'CLINICAL_MICROSCOPY', 'IMMUNO_SEROLOGY', 'MICROBIOLOGY', 'BLOOD_BANKING', 'MOLECULAR_BIOLOGY', 'OTHERS', name='machinetype'),
               existing_nullable=True)
        batch_op.drop_column('model')

    with op.batch_alter_table('instruments_model', schema=None) as batch_op:
        batch_op.add_column(sa.Column('machine_type', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instruments_model', schema=None) as batch_op:
        batch_op.drop_column('machine_type')

    with op.batch_alter_table('instruments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('model', mysql.VARCHAR(length=255), nullable=True))
        batch_op.alter_column('machine_type',
               existing_type=sa.Enum('HEMATOLOGY', 'CHEMISTRY', 'CLINICAL_MICROSCOPY', 'IMMUNO_SEROLOGY', 'MICROBIOLOGY', 'BLOOD_BANKING', 'MOLECULAR_BIOLOGY', 'OTHERS', name='machinetype'),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###
