"""empty message

Revision ID: 1e0271bda361
Revises: 053a4800c54a
Create Date: 2025-12-18 16:26:40.591215

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1e0271bda361'
down_revision = '053a4800c54a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instruments', schema=None) as batch_op:
        batch_op.drop_column('brand')
        batch_op.drop_column('machine_type')

    with op.batch_alter_table('instruments_model', schema=None) as batch_op:
        batch_op.alter_column('machine_type',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Enum('HEMATOLOGY', 'CHEMISTRY', 'CLINICAL_MICROSCOPY', 'IMMUNO_SEROLOGY', 'MICROBIOLOGY', 'BLOOD_BANKING', 'MOLECULAR_BIOLOGY', 'OTHERS', name='machinetype'),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instruments_model', schema=None) as batch_op:
        batch_op.alter_column('machine_type',
               existing_type=sa.Enum('HEMATOLOGY', 'CHEMISTRY', 'CLINICAL_MICROSCOPY', 'IMMUNO_SEROLOGY', 'MICROBIOLOGY', 'BLOOD_BANKING', 'MOLECULAR_BIOLOGY', 'OTHERS', name='machinetype'),
               type_=mysql.VARCHAR(length=255),
               nullable=False)

    with op.batch_alter_table('instruments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('machine_type', mysql.ENUM('HEMATOLOGY', 'CHEMISTRY', 'CLINICAL_MICROSCOPY', 'IMMUNO_SEROLOGY', 'MICROBIOLOGY', 'BLOOD_BANKING', 'MOLECULAR_BIOLOGY', 'OTHERS'), nullable=True))
        batch_op.add_column(sa.Column('brand', mysql.VARCHAR(length=255), nullable=True))

    # ### end Alembic commands ###
