"""Add status field to User

Revision ID: 2f6497265534
Revises: b1c4c8f2d7a8
Create Date: 2025-12-01 13:23:39.576359

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2f6497265534'
down_revision = 'b1c4c8f2d7a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_column('branch_name')

    with op.batch_alter_table('service_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status_after', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('is_monitor', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('monitored_days', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_logs', schema=None) as batch_op:
        batch_op.drop_column('monitored_days')
        batch_op.drop_column('is_monitor')
        batch_op.drop_column('status_after')

    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('branch_name', mysql.VARCHAR(length=255), nullable=True))

    # ### end Alembic commands ###
