"""empty message

Revision ID: 4b98abac4a99
Revises: e06c4cf784f6
Create Date: 2025-12-04 15:41:13.561520

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b98abac4a99'
down_revision = 'e06c4cf784f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('app_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('ticket_for', sa.String(length=20), nullable=True))
        batch_op.create_foreign_key(None, 'apps', ['app_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_logs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('ticket_for')
        batch_op.drop_column('app_id')

    # ### end Alembic commands ###
