"""empty message

Revision ID: 4bf6dee1f044
Revises: 4adb245a2107
Create Date: 2025-12-02 02:30:56.098703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bf6dee1f044'
down_revision = '4adb245a2107'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weekly_schedule_tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pm_schedule_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'preventive_maintenance_schedules', ['pm_schedule_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weekly_schedule_tasks', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('pm_schedule_id')

    # ### end Alembic commands ###
