"""empty message

Revision ID: 52104926d2fc
Revises: 641ed8706cba
Create Date: 2025-12-03 09:35:38.994223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52104926d2fc'
down_revision = '641ed8706cba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('service_types')
    # ### end Alembic commands ###
