"""empty message

Revision ID: 641ed8706cba
Revises: bb5e877d315c
Create Date: 2025-12-03 00:43:11.275440

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '641ed8706cba'
down_revision = 'bb5e877d315c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weekly_schedule_tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('app_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('ticket_for', sa.String(length=20), nullable=True))
        batch_op.alter_column('instrument_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.create_foreign_key(None, 'apps', ['app_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weekly_schedule_tasks', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('instrument_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
        batch_op.drop_column('ticket_for')
        batch_op.drop_column('app_id')

    # ### end Alembic commands ###
