"""empty message

Revision ID: 64a191034ec7
Revises: 65d9f87b72db
Create Date: 2025-12-08 05:55:27.081254

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '64a191034ec7'
down_revision = '65d9f87b72db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=mysql.ENUM('ADMIN', 'ENGINEER', 'CLIENT', 'SALES'),
               type_=sa.Enum('ADMIN', 'ENGINEER', 'SALES', 'CLIENT', name='userrole'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.Enum('ADMIN', 'ENGINEER', 'SALES', 'CLIENT', name='userrole'),
               type_=mysql.ENUM('ADMIN', 'ENGINEER', 'CLIENT', 'SALES'),
               existing_nullable=False)

    # ### end Alembic commands ###
