"""empty message

Revision ID: 65d9f87b72db
Revises: 4b98abac4a99
Create Date: 2025-12-04 15:52:47.979885

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '65d9f87b72db'
down_revision = '4b98abac4a99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('service_for', sa.String(length=20), nullable=True))
        batch_op.drop_column('ticket_for')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ticket_for', mysql.VARCHAR(length=20), nullable=True))
        batch_op.drop_column('service_for')

    # ### end Alembic commands ###
