"""empty message

Revision ID: 9ea8ca99ded8
Revises: 64a191034ec7
Create Date: 2025-12-08 10:13:47.249842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ea8ca99ded8'
down_revision = '64a191034ec7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('started_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('is_working', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.drop_column('is_working')
        batch_op.drop_column('started_date')

    # ### end Alembic commands ###
