"""empty message

Revision ID: bb5e877d315c
Revises: 8b5aba85e961
Create Date: 2025-12-03 00:32:37.818600

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bb5e877d315c'
down_revision = '8b5aba85e961'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_apps',
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('app_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['app_id'], ['apps.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('client_id', 'app_id')
    )
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('app_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('ticket_for', sa.String(length=20), nullable=True))
        batch_op.alter_column('instrument_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.create_foreign_key(None, 'apps', ['app_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('instrument_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
        batch_op.drop_column('ticket_for')
        batch_op.drop_column('app_id')

    op.drop_table('client_apps')
    # ### end Alembic commands ###
