"""empty message

Revision ID: c6db7f7dc77d
Revises: 9ea8ca99ded8
Create Date: 2025-12-08 16:53:54.543302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6db7f7dc77d'
down_revision = '9ea8ca99ded8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_sales_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['assigned_sales_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('assigned_sales_id')

    # ### end Alembic commands ###
