"""empty message

Revision ID: e5d72dd81e0d
Revises: c6db7f7dc77d
Create Date: 2025-12-08 17:02:16.669161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5d72dd81e0d'
down_revision = 'c6db7f7dc77d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('clients_ibfk_1'), type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('clients_ibfk_1'), 'users', ['assigned_sales_id'], ['id'])

    # ### end Alembic commands ###
